_('# Of Files')
_('About')
_('Active time')
_('Add Torrent')
_('Add torrent')
_('Address')
_('Admin')
_('Auto Managed')
_('Auto refresh:')
_('Ava')
_('Availability')
_('Clear')
_('Client')
_('Config')
_('Connect')
_('Connect to Daemon')
_('Connected to')
_('Connections')
_('DHT Nodes')
_('Delete .torrent file')
_('Delete downloaded files.')
_('Deluge : Torrent List')
_('Deluge Login')
_('Disable')
_('Disk Space')
_('Do not download')
_('Down Speed')
_('Download')
_('Downloaded')
_('ETA')
_('Enable')
_('Error')
_('Eta')
_('False')
_('File')
_('Filter on a keyword')
_('General')
_('High priority')
_('Highest priority')
_('Keyword')
_('Label')
_('Label torrent')
_('Login')
_('Logout')
_('Move')
_('Move torrent')
_('Name')
_('Next Announce')
_('No Incoming Connections')
_('No Label')
_('None')
_('Normal priority')
_('Not Connected to a daemon')
_('Off')
_('Options')
_('Other')
_('Password')
_('Password is invalid,try again')
_('Pause all')
_('Peers')
_('Pieces')
_('Private')
_('Progress')
_('Queue')
_('Queue Position')
_('Ratio')
_('Refresh page every:')
_('Remove')
_('Remove torrent')
_('Restart')
_('Resume all')
_('Save')
_('Search')
_('Seed rank')
_('Seeders')
_('Seeding time')
_('Select All')
_('Set')
_('Set Timeout')
_('Share Ratio')
_('Size')
_('Speed')
_('Start')
_('Stop')
_('Submit')
_('Torrent list')
_('Total Size')
_('Tracker')
_('Tracker Status')
_('True')
_('Up Speed')
_('Update')
_('Upload')
_('Uploaded')
_('seconds')
