.TH DELUGE-WEB 1 "May 2017" "1.3.15"

.SH NAME
deluge-web - a bittorrent client ajax web interface

.SH SYNOPSIS
.B deluge-web [options]

.SH DESCRIPTION
Deluge utilizes a client/server model, with 'deluged' being the daemon process and 'deluge-web' being used to launch an ajax web based user-interface.
.P
The default password is 'deluge'.

.SH OPTIONS
.SS General Options
.TP
.BI -c\  path \fR,\ \fB--config= path
Set the config directory location.

.SS Web Options
.TP
.BI -b\  path \fR,\ \fB--base= path
Set the base path that the web ui is running on (proxying)
.TP
.B -f, --fork
Fork the web interface process into the background
.TP
.BI -i\  ip_address \fR,\ \fB--interface= ip_address
Binds the webserver to a specific IP address
.TP
.BI -p\  port \fR,\ \fB--port= port
Sets the port to be used for the webserver
.TP
.B --profile
Profile the webserver code
.TP
.B --no-ssl
Forces the webserver to disable ssl
.TP
.B --ssl
Forces the webserver to use ssl

.SS Logging Options
.TP
.BI -l\  file \fR,\ \fB--logfile= file
Output to designated logfile instead of stdout
.TP
.BI -L\  loglevel \fR,\ \fB--loglevel= loglevel
Set the log level (default is error):
.B none, info, warning, error, critical, debug
.TP
.B -q, --quiet
Sets the log level to 'none', same as `\-L none`

.SS Help Options
.TP
.B -v, --version
Show program's version number and exit.
.TP
.B -h, --help
Show help message and exit.

.SH SEE ALSO
.BR deluge(1),
.BR deluged(1),
.BR deluge-console(1)

.SH AUTHORS
.B Deluge Team: http://www.deluge-torrent.org
