.TH DELUGE-CONSOLE 1 "May 2017" "1.3.15"

.SH NAME
deluge-console - a bittorrent client curses interface

.SH SYNOPSIS
.B deluge-console [options]

.SH DESCRIPTION
Deluge utilizes a client/server model, with 'deluged' being the daemon process and 'deluge-console' being used to launch a console user-interface.
.P
You can pass console commands directly from the command line and run multiple commands by separating them with a semi-colon (;).
.SS Console Commands:
    info quit pause help resume del plugin cache add exit connect debug rm config recheck halt

.SH OPTIONS
.SS General Options
.TP
.BI -c\  path \fR,\ \fB--config= path
Set the config directory location.

.SS Logging Options
.TP
.BI -l\  file \fR,\ \fB--logfile= file
Output to designated logfile instead of stdout
.TP
.BI -L\  loglevel \fR,\ \fB--loglevel= loglevel
Set the log level (default is error):
.B none, info, warning, error, critical, debug
.TP
.B -q, --quiet
Sets the log level to 'none', same as `\-L none`

.SS Help Options
.TP
.B -v, --version
Show program's version number and exit.
.TP
.B -h, --help
Show help message and exit.

.SH SEE ALSO
.BR deluge(1),
.BR deluged(1),
.BR deluge-web(1)

.SH AUTHORS
.B Deluge Team: http://www.deluge-torrent.org
