.TH DELUGE-CONSOLE 1 "November 2014" "1.3.11"

.SH NAME
deluge-console - a bittorrent client curses interface

.SH SYNOPSIS
.B deluge-console [options]

.SH DESCRIPTION
.br
.P
Deluge utilizes a client/server model, with 'deluged' being the daemon process and 'deluge-console' being used to launch a console user-interface.
.br
.P
You can pass console commands directly from the command line, see `deluge-console \-\-help` for a list of commands.
Run multiple commands by separating them with a semi-colon (;).

.SH OPTIONS
See `deluge`.

.SH SEE ALSO
.B Homepage:
http://www.deluge-torrent.org/

.SH AUTHOR
This manual page was written by Andrew Resch <andrewresch@gmail.com>.
.br
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 or any later version published by the Free Software Foundation
.br
