.TH DELUGE 1 "November 2014" "1.3.11"

.SH NAME
deluge - a bittorrent client

.SH SYNOPSIS
.B deluge [options] [torrent]

.SH DESCRIPTION
.br
.P
Deluge utilizes a client/server model, with 'deluged' being the daemon process and 'deluge' being used to launch a user-interface.
.br
.P
By default, Deluge will run in 'Classic' mode where the daemon functionality will be hidden and the GtkUI will automatically launch a 'deluged' process.  You can turn this off in the Preferences dialog.

.SH OPTIONS
.TP
.I [torrent]
List of ".torrent" files to add to the download queue.
.TP
.I --version
Show program's version number and exit.
.TP
.I -h, --help
Show this help message and exit.
.TP
.I -c CONFIG, --config=CONFIG
Sets the configuration path.
.TP
.I -u UI, --ui=UI
The UI that you wish to launch, current options include: gtk, web or console
.TP
.I -l LOGFILE, --logfile=LOGFILE
Output to designated logfile instead of stdout
.TP
.I -L LOGLEVEL, --loglevel=LOGLEVEL
Set the log level (default is error): none, info, warning, error, critical, debug
.TP
.I -q --quiet
Sets the log level to 'none', this is the same as `\-L none`
.TP
.I -s DEFAULT_UI, --set-default-ui=DEFAULT_UI
Sets the default UI to be run when no UI is specified

.SH SEE ALSO
.B Homepage:
http://www.deluge-torrent.org/

.SH AUTHOR
This manual page was written by Andrew Resch <andrewresch@gmail.com>.
.br
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 or any later version published by the Free Software Foundation
.br
