.TH DELUGED 1 "May 2017" "1.3.15"

.SH NAME
deluged - a bittorrent client daemon

.SH SYNOPSIS
.B deluged [options]

.SH DESCRIPTION
Deluge utilizes a client/server model, with 'deluged' being the daemon process and 'deluge' being used to launch a user-interface.
.P
By default, 'deluged' will run as a daemon, to prevent this you can run deluged with the \-d option.  This option is useful for running deluged with the start-stop-daemon.

.SH OPTIONS
.SS General Options
.TP
.BI -c\  path \fR,\ \fB--config= path
Set the config directory location.

.SS Daemon Options
.TP
.BI -p\  port \fR,\ \fB--port= port
Port daemon will listen on, default is 58846
.TP
.BI -i\  ip_address \fR,\ \fB--interface= ip_address
Interface daemon will listen for bittorrent connections on, this should be an IP address
.TP
.BI -u\  ip_address \fR,\ \fB--ui-interface= ip_address
Interface daemon will listen for UI connections on, this should be an IP address
.TP
.B -d, --do-not-daemonize
Do not daemonize
.TP
.BI -P\  file \fR,\ \fB--pidfile= file
Use pidfile to store process id

.SS Logging Options
.TP
.BI -l\  file \fR,\ \fB--logfile= file
Output to designated logfile instead of stdout
.TP
.BI -L\  loglevel \fR,\ \fB--loglevel= loglevel
Set the log level (default is error):
.B none, info, warning, error, critical, debug
.TP
.B -q, --quiet
Sets the log level to 'none', same as `\-L none`

.SS Help Options
.TP
.B -v, --version
Show program's version number and exit.
.TP
.B -h, --help
Show help message and exit.

.SH SEE ALSO
.BR deluge(1),
.BR deluge-web(1),
.BR deluge-console(1)

.SH AUTHORS
.B Deluge Team: http://www.deluge-torrent.org
