name: mypy

on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-linux:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: "pip"

      # This is needed for pygobject-stubs
      - name: Install system packages
        run: |
          sudo apt install libgirepository1.0-dev

      - name: Install dependencies
        run: |
          pip install --upgrade pip wheel
          pip install -r requirements.txt -r requirements-tests.txt
          pip install -e .

      - name: Run mypy
        run: |
          mypy deluge/
